name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main  # Workflow, sadece "main" dalına push edildiğinde çalışır

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodları Depodan Çek
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Azure’a Giriş Yap
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. ACR'ye Kimlik Doğrulama
    - name: Authenticate with Azure Container Registry
      run: |
        az acr login --name se4453finalacr  # Container Registry adı ile güncelleme yapıldı

    # 4. Docker Image Oluştur ve ACR'ye Gönder
    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t se4453finalacr.azurecr.io/flask-app:latest .
        docker push se4453finalacr.azurecr.io/flask-app:latest

    # 5. App Service'i ACR'deki Yeni Image'i Kullanacak Şekilde Yapılandır
    - name: Deploy to Azure App Service
      run: |
        az webapp config container set --name SE4453app --resource-group SE4453Final --docker-custom-image-name se4453finalacr.azurecr.io/flask-app:latest --docker-registry-server-url https://se4453finalacr.azurecr.io --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}
