name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Login to Azure using Service Principal credentials stored in GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login to Azure Container Registry (ACR)
      - name: Login to ACR
        run: |
          az acr login --name se4453finalacr

      # 4. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t se4453finalacr.azurecr.io/accessfit:latest .

      # 5. Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push se4453finalacr.azurecr.io/accessfit:latest

      # 6. Deploy to Azure App Service
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: SE4453app
          slot-name: production
          images: se4453finalacr.azurecr.io/accessfit:latest
